### ISSUE TITLE
Reduce verbosity of automatic prunes

### ISSUE THREAD

**Issue by chris-feist** [claygregory/serverless-prune-plugin#11]
When auto pruning, there should be minimal logs. Consider adding a `debug` or `verbose` option for automatic pruning to get detailed logs, like what's currently output.

With the current output, the prune logs push the deployed service information off the screen for big projects.

**Comment by claygregory** [comment]
Yeah, I can see that; I'll add to my queue of things to work on. Thanks for the suggestion @chris-feist

**Comment by manwaring** [comment]
@claygregory I see that the code changes were made but the latest version (1.4.1) doesn't have them - is there anything blocking this feature being released?  If it's something I can help with I'd love to contribute!

**Comment by claygregory** [comment]
Hey all — very sorry, this issue completely fell off my radar. But better late than never, right? The upcoming Serverless 3.x output API provides a new, standardized way of handling progress and notifications. This plugin will have support out of the gate with the new API, cleaning up this long-standing annoyance.

I'm going to close this issue and use the 3.x output API migration (#35) to track this to completion.
