### ISSUE TITLE
Add command to list number of versions per function?

### ISSUE THREAD

**Issue by kevlarr** [claygregory/serverless-prune-plugin#13]
The plugin lets you manually prune to the specified number of versions, but would it be possible to add a command that would *list* the number of versions per function, prior to just choosing a number and commencing prune?

Not sure if this would really be that desirable, but it's a little frustrating that Serverless/AWS in general don't surface those numbers easily.

**Comment by claygregory** [comment]
Hey @kevlarr 

While you do have to provide a trial value for `n`, you can get these counts with the dry-run option:
```
sls prune -n 5 --dryRun
```

You'll get something like:
```
Serverless: Prune: Querying for deployed versions
Serverless: Prune: pipeline-stg-index has 6 additional versions published and 0 aliases, 5 versions selected for deletion
Serverless: Prune: pipeline-stg-downloadSt1 has 5 additional versions published and 0 aliases, 4 versions selected for deletion
Serverless: Prune: pipeline-stg-downloadSt2 has 6 additional versions published and 0 aliases, 5 versions selected for deletion
Serverless: Prune: pipeline-stg-downloadPd1 has 6 additional versions published and 0 aliases, 5 versions selected for deletion
```

You'll get a listing of every function, number of non-$latest versions, as well as how many versions would be pruned to reach the specified `n`-deployment—no deletions will actually be performed. For your purpose, just provide a small `-n` and ignore the deletion candidate count.

Does that solve your immediate need?

**Comment by kevlarr** [comment]
@claygregory Apologies, I missed the `--dryRun` - that's perfect actually! Thank you for the excellent plugin.
