### ISSUE TITLE
When added retrospectively, prunes to leave very old versions

### ISSUE THREAD

**Issue by wheresrhys** [claygregory/serverless-prune-plugin#14]
![image](https://user-images.githubusercontent.com/447559/61457431-3143eb00-a960-11e9-9b81-07e1bfd8414f.png)

I'm guessing that the plugin does an alphabetical sort, not numeric, when deciding what to delete, so 9 and 8 appear to be more recent than e.g. 64 and 63

**Comment by JustinTArthur** [comment]
Pull request #15 looks good.

**Comment by claygregory** [comment]
Closed via #15

**Comment by wheresrhys** [comment]
Thanks. Will try it out today
