### ISSUE TITLE
Using plugin with `versionFunctions: false`

### ISSUE THREAD

**Issue by GarrisonD** [claygregory/serverless-prune-plugin#23]
Hi 👋 

As far as I understand using this plugin in conjunction with `versionFunctions: false` is useless, am I right?

**Comment by GarrisonD** [comment]
@claygregory And maybe you know how to solve the issue I faced: I noticed that in the S3 bucket I have folders for 5 las releases like `1606738205351-2020-11-30T12:10:05.351Z/` with AWS Lambda function code ZIP, layer ZIP and some `compiled-cloudformation-template.json`. And I don't know how to prune them...

**Comment by claygregory** [comment]
Hey @GarrisonD,

That's right, this plugin is pointless if you're not publishing versions to reap. And for a lot of people, `versionFunctions: false` makes a lot of sense.

As for the S3 deployment bucket, this plugin isn't really concerned with the intermediate deploy artifacts as they tend not to be a problem for most people: S3 is cheap and boundless (unlike deployed versions). But, if you do want to keep things tidy there, I would recommend checking out [S3 object lifecycle management](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html). You can configure S3 rules to migrate artifacts to a lower durability level, or even delete entirely, after a certain age.

Hope that helps!

**Comment by GarrisonD** [comment]
I discovered that serverless is keeping assets for only 5 last deployments. So on any new deployment, one new folder with new assets appears and the oldest one folder gets removed automatically. So there is no problem with an S3 bucket growing in size 👍

**Comment by GarrisonD** [comment]
But it's interesting for me where this number 5 comes from and whether it can be changed somehow to 1...
