### ISSUE TITLE
serverless framework deprecation warning

### ISSUE THREAD

**Issue by pharindoko** [claygregory/serverless-prune-plugin#28]
Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - Prune for "number", "stage", "region", "function", "layer", "includeLayers", "dryRun"
            Please report this issue in plugin issue tracker.

**Comment by claygregory** [comment]
Hi @pharindoko—I believe what you're referring to here was fixed in PR #27 and released in version [1.5.0](https://github.com/claygregory/serverless-prune-plugin/releases/tag/v.1.5.0).

**Comment by pharindoko** [comment]
@claygregory 
damn right 😄  sorry...
updated my version to 1.5.0 - works ...
