### ISSUE TITLE
Autoprune?

### ISSUE THREAD

**Issue by hassankhan** [claygregory/serverless-prune-plugin#3]
It would be pretty useful if we could set a custom var or something representing `n` last versions and have the plugin automatically prune instead of only being able to do it via CLI.

**Comment by claygregory** [comment]
Hi @hassankhan,

Seems reasonable to hook prune into the deployment lifecycle with the `after:deploy:deploy` event so it can be configured to run automatically, with `n` provided in `serverless.yml`. I'll plan to implement sometime in next few days.

**Comment by claygregory** [comment]
Actually, this turned out to be easier to add than I thought. I just published version 1.1.0 with this feature, see [documentation](https://github.com/claygregory/serverless-prune-plugin#automatic-pruning) for details.

**Comment by hassankhan** [comment]
Oh wow thanks for the lightning-fast implementation! I was gauging interest because I wanted to make a PR, but you beat me to it! 😄

**Comment by claygregory** [comment]
Definitely a useful feature, so the PR would've been welcome! But either way, no worries — thanks for the idea!
