### ISSUE TITLE
Should not auto prune when running with `sls deploy --noDeploy`

### ISSUE THREAD

**Issue by ajmath** [claygregory/serverless-prune-plugin#4]
I was surprised to see auto pruning being attempted when running with the `--noDeploy` flag.

**Comment by claygregory** [comment]
Oh wow, I actually didn't even know about the `--noDeploy` flag. Thanks for report — should be fixed in [version 1.1.1](https://github.com/claygregory/serverless-prune-plugin/tree/v1.1.1)

**Comment by ajmath** [comment]
Thanks for the quick fix!
