### ISSUE TITLE
Add/ adapt additional Documentation

### ISSUE THREAD

**Issue by willKo** [claygregory/serverless-prune-plugin#7]
Hi, 
first of all great plugin, but there could be more documentiation regarding the options: 
![image](https://user-images.githubusercontent.com/5822698/31435069-a4047c4c-ae7e-11e7-8c4a-88f5dee4843a.png)

E.g. The --stage option is also available not sure if there are more options possible. 
I just tried it and was glad it worked.

**Comment by claygregory** [comment]
Hi,

Yes, you're correct, the `--region` and `--stage` options can be used just as in other `sls` commands. I've added both to the `--help` output in v1.3.0, as well as documented in the README.

Thanks for bringing this up!
