### ISSUE TITLE
Automatic Pruning not working

### ISSUE THREAD

**Issue by ZhangVic** [claygregory/serverless-prune-plugin#9]
hi, Clay Gregory.
I used this plugin in my serverless project.

Actually I need to manage manay serverless projects and each of them has several Lambda functions.

And I deploy these serverless projects by using CloudFormation in CodePipeline deploy stage.
So in my scenario: 
①I need to `sls package`  to get CF template file 
② upload jars to a specified location in S3
③ use CF with the template file generated in step ① to update a stack.

I update serverless.yml with 
```
custom:
  prune:
    automatic: true
    number: 10
```
In this plugin `ReadMe` file, this config will automatic pruning. but it doesn't work in my situation.
Any idea?

**Comment by claygregory** [comment]
Hi @ZhangVic,

So it sounds like you're using sls to package, but not to deploy your functions, correct? Automatic pruning is attached to the `sls deploy` event hook; so without using the framework to deploy, you won't be able to make use of automatic pruning. However, you can likely achieve a similar result by adding a call to `sls prune -n 10` in your build process.

**Comment by ZhangVic** [comment]
Hi, @claygregory ,
Thank you very much for your reply, I understand the reason now.
But add `sls prune -n 10` is not suitable in my scenario.

Because I will deploy about 70 lambda functions in several deploy actions in my codepipeline.
And to ensure the consistency of all lambda function versions, we developed a new function to switch functions' version in one step. 

If any of these funtions failed in build/deploy/version up step, our new function will rollback all lambda functions. 
We deploy this new function to ensure our product no-down time feature.

So I can not add `sls prune -n 10` in build step since the deploy is not confirmed yet.

But I think I may use `serverless-prune-plugin` after deploy and version up is confirmed, maybe using another lambda to handle this.

Thank you again for your reply,
